// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbgfovckilwzzgitxjeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZ2ZvdmNraWx3enpnaXR4amVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODMwOTUsImV4cCI6MjA4NTM1OTA5NX0.PvQ2-7aIYcOM8Kt3IVd8r1g4BIN7xvyZOarRHZW_jVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});